use_frameworks!

target 'UITabBarController-KTHidden_Example' do
  pod 'UITabBarController-KTHidden', :path => '../'

  target 'UITabBarController-KTHidden_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
